/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author DEIRY
 */
public class VistaInicio extends javax.swing.JFrame {

    private JTabbedPane panel;
    private VistaInsertar vistaInsert;
    private VistaEliminar vistaEliminar;
    private VistaInvertir vistaInvertir;
    private VistaModificar vistaModificar;
    private VistaOrdenar vistaOrdenar;
    private VistaSubhilera vistaSub;
    private VistaPalindromo vistaPalindromo;
    private VistaAnagrama vistaAnagrama;

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
        panel = new JTabbedPane();
        vistaInsert = new VistaInsertar();
        vistaEliminar = new VistaEliminar();
        vistaModificar = new VistaModificar();
        vistaInvertir = new VistaInvertir();
        vistaOrdenar = new VistaOrdenar();
        vistaSub = new VistaSubhilera();
        vistaPalindromo = new VistaPalindromo();
        vistaAnagrama = new VistaAnagrama();
        panel.setBackground(Color.white);

        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/anagrama.png")), vistaAnagrama, "Verificar si Hilera es anagrama");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/palindro.png")), vistaPalindromo, "Verificar Hilera si es palindromo");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/subHilera.png")), vistaSub, "Extraer SubHilera");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/ordenar.png")), vistaOrdenar, "Ordenar Hilera");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/insert.png")), vistaInsert, "Insertar Hilera");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/delete.png")), vistaEliminar, "Eliminar Hilera");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/modify.png")), vistaModificar, "Modificar Hilera");
        panel.addTab("", new ImageIcon(getClass().getResource("/Vista/Recursos/reverse.png")), vistaInvertir, "Invertir Hilera");
        panel.setSelectedIndex(4);
        //    mostrarPaneles();
        this.panelMundo.add(panel);
        
    }

    public void paintPanel() {
        this.panelMundo.repaint();
        this.panelMundo.revalidate();
    }

    /**
     * La situiente funcion limpia un panel JPanel para posteriormente dibujar
     * el panel que se necesita
     *
     * @param jp panel que se va limpiar
     */
    public void cleanPanel(JPanel jp) {
        jp.removeAll();
        jp.repaint();
        jp.revalidate();
    }

    /**
     * La siguiente funcion agregar el panel que se va usar jp en el panel
     * JPanelWork
     *
     * @param jp es el panel que se va agregar en el panel JpOri
     */
    public void setPanel(JPanel jp, JPanel jpOri) {
        jpOri.add(jp);
        jpOri.repaint();
        jpOri.revalidate();
    }

    public void mostrarPaneles() {
        cleanPanel(panelMundo);
        setPanel(vistaInsert, panelMundo);
        vistaInsert.setVisible(true);
        /*  paintPanel();
        vistaEliminar.setVisible(true);
        paintPanel();
        vistaInvertir.setVisible(true);
        paintPanel();
        vistaModificar.setVisible(true);
        paintPanel();
        vistaOrdenar.setVisible(true);
        paintPanel();
        vistaSub.setVisible(true);
        paintPanel();
        vistaPalindromo.setVisible(true);
        paintPanel();
        vistaAnagrama.setVisible(true);
        paintPanel();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaVisualizacion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        panelComentario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelRespuesta = new javax.swing.JLabel();
        panelMundo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        AreaVisualizacion.setColumns(20);
        AreaVisualizacion.setRows(5);
        jScrollPane1.setViewportView(AreaVisualizacion);

        jLabel2.setText("Secuencia de la hilera");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        panelComentario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Respuesta");

        javax.swing.GroupLayout panelComentarioLayout = new javax.swing.GroupLayout(panelComentario);
        panelComentario.setLayout(panelComentarioLayout);
        panelComentarioLayout.setHorizontalGroup(
            panelComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComentarioLayout.createSequentialGroup()
                .addGroup(panelComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComentarioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelRespuesta))
                    .addGroup(panelComentarioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelComentarioLayout.setVerticalGroup(
            panelComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComentarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(labelRespuesta)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        panelMundo.setBackground(new java.awt.Color(255, 255, 255));
        panelMundo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMundo, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panelComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaVisualizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRespuesta;
    private javax.swing.JPanel panelComentario;
    private javax.swing.JPanel panelMundo;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que recupera un objeto tipo JTextField con name CuadroString
     *
     * @return retorna un objeto JTextField
     */
    public JTextField retornaCuadroString() {
        System.out.println("vista cuadro" + vistaInsert.retornaCuadroString());
        return vistaInsert.retornaCuadroString();
    }

    /**
     * Metdo que recupera un objeto tipo JButton con name cargaString
     *
     * @return retorna un objeto tipo JButton
     */
    public JButton retornaBotonCargaString() {
        return vistaInsert.retornaBotonCargaString();
    }

    /**
     * Metodo que recupera un objeto tipo JTextArea con name AreaVisualizacion
     *
     * @return retorna un objeto tipo JTextArea
     */
    public JTextArea retornaAreaVisualizacion() {
        return AreaVisualizacion;
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name valInicial
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaValInicialBorrado() {
        return vistaEliminar.retornaValInicialBorrado();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name numerElementos
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaNumeroElementosBorrado() {
        return vistaEliminar.retornaNumeroElementosBorrado();
    }

    /**
     * Metodo que recupera un objeto tipo JComboBox con name RespuestaBorrado
     *
     * @return un objeto tipo JComboBox
     */
    public JComboBox retornaComboBorrado() {
        return vistaEliminar.retornaComboBorrado();

    }

    /**
     * Metodo que recupera un objeto tipo JButton con name borradoEditado
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotonBorrado() {
        return vistaEliminar.retornaBotonBorrado();
    }

    /**
     * Metodo que recupera un objeto tipo JLabel con name Respuesta
     *
     * @return un objeto tipo JLabel
     */
    public JLabel retornaRespuesta() {
        return vistaEliminar.retornaRespuesta();
    }

    /**
     * Metodo que recupera un objeto tipo JButton con name VerificaPalindromo
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotonPalindromo() {
        return vistaPalindromo.retornaBotonPalindromo();
    }

    /**
     * Metodo que recupera un objeto tipo JButton con name BotonOrdenar
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotonOrdenar() {
        return vistaOrdenar.retornaBotonOrdenar();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name cuadroAnagrama
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaCuadroAnagrama() {
        return vistaAnagrama.retornaCuadroAnagrama();
    }

    /**
     * Metodo que recupera un objeto tipo JButton con name botonAnagrama
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotonAngrama() {
        return vistaAnagrama.retornaBotonAngrama();
    }

    /**
     * Metodo que recupera un objeto tipo JButton con name botonInvertir
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotonInvertir() {
        return vistaInvertir.retornaBotonInvertir();
    }

    /**
     * Metodo que recupera un objeto tipo JButton con name botonModificar
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotonModificar() {
        return vistaModificar.retornaBotonModificar();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name cuadroModificar
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaCuadroModificar() {
        return vistaModificar.retornaCuadroModificar();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name cuadroPosModicar
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaPosModificar() {
        return vistaModificar.retornaPosModificar();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name
     * cuadroCantModificar
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaCantModificar() {
        return vistaModificar.retornaCantModificar();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name
     * posicionInicialSubString
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaPosicionInicialSubString() {
        return vistaSub.retornaPosicionInicialSubString();
    }

    /**
     * Metodo que recupera un objeto tipo JTextField con name
     * numPosicionSubString
     *
     * @return un objeto tipo JTextField
     */
    public JTextField retornaNumPosicionesSubString() {
        return vistaSub.retornaNumPosicionesSubString();
    }

    /**
     * Metodo que recupera un objeto tipo JButton con name ejecutaSubString
     *
     * @return un objeto tipo JButton
     */
    public JButton retornaBotoEjecutarSubString() {
        return vistaSub.retornaBotoEjecutarSubString();
    }

    /**
     * Metodo para mostrar la respuesta en el panel de observaciones
     *
     * @return Obejto tipo JLabel
     */
    public JLabel retornaRespuestaCom() {
        return labelRespuesta;
    }

    /**
     * Metodo que retorna el cuadro de texto para agregar una hilera a la lista
     * orignal
     *
     * @return Cuadro de texto con el string a agregar
     */
    public JTextField retornaCuadroAgregar() {
        return vistaInsert.retornaCuadroAgregar();
    }

    /**
     * Metodo que retorna el boton para para agregar una hilera a la lista
     * orignal
     *
     * @return Boton con el string a agregar
     */
    public JButton retornaBotonAgregar() {
        return vistaInsert.retornaBotonAgregar();
    }
}
