/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Validaciones;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author DEIRY
 */
public class VistaEliminar extends javax.swing.JPanel {

    /**
     * Creates new form VistaEliminar
     */
    public VistaEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        RespuestaBorrado = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        valInicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numerElementos = new javax.swing.JTextField();
        borradoEditado = new javax.swing.JButton();
        Respuesta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Eliminar Hilera Completa?");

        RespuestaBorrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Respuesta", "Si", "No" }));
        RespuestaBorrado.setEnabled(false);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Borrado"));

        jLabel5.setText("Posicion Inicial");

        valInicial.setEnabled(false);
        valInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valInicialKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad caracteres");

        numerElementos.setEnabled(false);
        numerElementos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numerElementosKeyTyped(evt);
            }
        });

        borradoEditado.setBackground(new java.awt.Color(131, 196, 76));
        borradoEditado.setText("Borrar");
        borradoEditado.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Respuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valInicial)
                    .addComponent(numerElementos, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(borradoEditado)
                .addGap(34, 34, 34))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(valInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numerElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(borradoEditado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(Respuesta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(RespuestaBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RespuestaBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valInicialKeyTyped
        // TODO add your handling code here:
        if(Validaciones.numeros(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_valInicialKeyTyped

    private void numerElementosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numerElementosKeyTyped
        // TODO add your handling code here:
        if(Validaciones.numeros(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_numerElementosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Respuesta;
    private javax.swing.JComboBox<String> RespuestaBorrado;
    private javax.swing.JButton borradoEditado;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JTextField numerElementos;
    private javax.swing.JTextField valInicial;
    // End of variables declaration//GEN-END:variables
    
    /**
 * Metodo que recupera un objeto tipo JTextField  con name valInicial 
 * @return un objeto tipo JTextField
 */
public JTextField retornaValInicialBorrado()
{
    return valInicial;
}

/**
 * Metodo que recupera un objeto tipo JTextField con name numerElementos 
 * @return un objeto tipo JTextField
 */

public JTextField retornaNumeroElementosBorrado()
{
    return numerElementos;
}


/**
 * Metodo que recupera un objeto tipo JComboBox con name RespuestaBorrado 
 * @return  un objeto tipo JComboBox
 */
public JComboBox retornaComboBorrado()
{
    return RespuestaBorrado;
    
}

/**
 * Metodo que recupera un objeto tipo JButton con name borradoEditado
 * @return un objeto tipo JButton
 */

public JButton retornaBotonBorrado()
{
    return borradoEditado;
}

/**
 * Metodo que recupera un objeto tipo JLabel con name Respuesta  
 * @return un objeto tipo JLabel
 */

public JLabel retornaRespuesta()
{
    return Respuesta;
}

}
