/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Validaciones;
import java.awt.ComponentOrientation;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DEIRY
 */
public class VistaInsertar extends javax.swing.JPanel {

    /**
     * Creates new form VistaInsertar
     */
    public VistaInsertar() {
        initComponents();

    }
    
    

    /**
     * Metodo que recupera un objeto tipo JTextField con name CuadroString
     *
     * @return retorna un objeto JTextField
     */
    public JTextField retornaCuadroString() {
        return CuadroString;
    }

    /**
     * Metdo que recupera un objeto tipo JButton con name cargaString
     *
     * @return retorna un objeto tipo JButton
     */
    public JButton retornaBotonCargaString() {
        return cargaString;
    }

    /**
     * Metodo que retorna el cuadro de texto para agregar una hilera a la lista
     * orignal
     *
     * @return Cuadro de texto con el string a agregar
     */
    public JTextField retornaCuadroAgregar() {
        return CuadroAgregar;
    }

    /**
     * Metodo que retorna el boton para para agregar una hilera a la lista
     * orignal
     *
     * @return Boton con el string a agregar
     */
    public JButton retornaBotonAgregar() {
        return agregarString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CuadroString = new javax.swing.JTextField();
        cargaString = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CuadroAgregar = new javax.swing.JTextField();
        agregarString = new javax.swing.JButton();
        next = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(480, 373));

        jLabel1.setText("Ingresar Hilera Original");

        CuadroString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CuadroStringKeyTyped(evt);
            }
        });

        cargaString.setBackground(new java.awt.Color(131, 196, 76));
        cargaString.setText("Ingresar");
        cargaString.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Agregar Hilera orginal");

        CuadroAgregar.setEnabled(false);
        CuadroAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CuadroAgregarKeyTyped(evt);
            }
        });

        agregarString.setBackground(new java.awt.Color(131, 196, 76));
        agregarString.setText("Agregar");
        agregarString.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarString.setEnabled(false);

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/next.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CuadroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cargaString, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CuadroString, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agregarString, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuadroString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargaString, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuadroAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarString, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(next)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CuadroStringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CuadroStringKeyTyped
        // TODO add your handling code here:
        char carac = evt.getKeyChar();
        if (!Validaciones.letras(carac)) {
            evt.consume();
        } else if (!Validaciones.minuscula(carac)) {
            evt.setKeyChar((char) (carac + 32));
        }


    }//GEN-LAST:event_CuadroStringKeyTyped

    private void CuadroAgregarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CuadroAgregarKeyTyped
        // TODO add your handling code here:
        char carac = evt.getKeyChar();
        if (!Validaciones.letras(carac)) {
            evt.consume();
        } else if (!Validaciones.minuscula(carac)) {
            evt.setKeyChar((char) (carac + 32));
        }
    }//GEN-LAST:event_CuadroAgregarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CuadroAgregar;
    private javax.swing.JTextField CuadroString;
    private javax.swing.JButton agregarString;
    private javax.swing.JButton cargaString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel next;
    // End of variables declaration//GEN-END:variables



    public javax.swing.JLabel getNext() {
        return next;
    }
}
